name: Build Latest

on: [push]

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' 

      - run: dotnet publish -r win-x64 -c Release
      - run: dotnet publish -r win-arm64 -c Release

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-x64
          path: BBDown\bin\Release\net5.0\win-x64\native\BBDown.exe

      - name: Upload Artifact[win-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-arm64
          path: BBDown\bin\Release\net5.0\win-arm64\native\BBDown.exe
  

  build-linux-x64:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' 
      - run: sudo apt-get install libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish -r linux-x64 -c Release
      - run: strip BBDown/bin/Release/net5.0/linux-x64/native/BBDown
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-x64
          path: BBDown/bin/Release/net5.0/linux-x64/native/BBDown

  build-linux-arm64:
    
    runs-on: ubuntu-18.04
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-arm64-20201022204150-b2c2436
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' 
      - run: dotnet publish -r linux-arm64 -c Release -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64
      - run: aarch64-linux-gnu-strip BBDown/bin/Release/net5.0/linux-arm64/native/BBDown
      
      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-arm64
          path: BBDown/bin/Release/net5.0/linux-arm64/native/BBDown


  build-mac-x64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' 
      - run: dotnet publish -r osx-x64 -c Release
      - run: strip BBDown/bin/Release/net5.0/osx-x64/native/BBDown
      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_osx-x64
          path: BBDown/bin/Release/net5.0/osx-x64/native/BBDown
